name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag Docker image [incremental tag]
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/myimage:${{ github.ref_name }}" .
        working-directory: Docker

      - name: Build and tag Docker image [latest tag]
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/myimage:latest" .
        working-directory: Docker

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/myimage:${{ github.ref_name }}"
        working-directory: Docker

      - name: Push Docker image to Docker Hub [latest tag]
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/myimage:latest"
        working-directory: Docker

      - name: Set output for next workflow
        run: |
          echo "image_tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
