name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your EKS cluster region

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name bogdan-eks-cluster --region us-east-1

      - name: Apply Kubernetes manifests
        run: |
            kubectl apply -f deployment.yml
            kubectl apply -f lb_service.yml
        working-directory:  Kubernetes-Manifests
